### ISSUE TITLE
Bug with new version (0.0.5)

### ISSUE THREAD

**Issue by NZ-Wanderer** [tanukinomori/DSPMod#1]
Seem to have a little bug with the latest version...
![Untitled](https://user-images.githubusercontent.com/447796/111227819-05eb3500-8648-11eb-8023-5d09b7bffe84.jpg)
If I disable your mod it is fine...
Strange, when I reload the game it works as it should, very weird..
BUT when I go back into sail mode again it reappears...

**Comment by tanukinomori** [comment]
Thanks for the report.
Let me check a few things for you.
Does the same thing happen if I delete the config file?
What mods are you using with it?
Does it happen even if I disable all other mods?

**Comment by tanukinomori** [comment]
Can you attach an error log such as LogOutput.log?

**Comment by NZ-Wanderer** [comment]
pic of mods used, and the only logoutput.log I could find...
![Capture](https://user-images.githubusercontent.com/447796/111256282-9e4fdc80-867d-11eb-84bb-8e42829a2a13.JPG)
[LogOutput.log](https://github.com/tanukinomori/DSPMod/files/6146124/LogOutput.log)
I will try deleting the config file and see if that helps...

**Comment by NZ-Wanderer** [comment]
Deleting the config did not solve the problem...

**Comment by tanukinomori** [comment]
I've installed the mods shown in the image and checked them out, and they seem to be working fine without any problems.

**Comment by tanukinomori** [comment]
Can you please attach the configuration files for each mod?
Also, can you tell me what the settings are when the game starts and what the screen settings are?

**Comment by tanukinomori** [comment]
Can I ask you to install and check CruiseAssist only?

**Comment by NZ-Wanderer** [comment]
My default game resolution is 3840x2160 full screen, BUT when the game loads, the UIlayoutheightfix mod sets the UI to 2160 (not the default 1080..
Here is the config files zipped [config.zip](https://github.com/tanukinomori/DSPMod/files/6147464/config.zip)
(there may be one or two configs in there from mods I uninstalled as I never bothered checking for configs) the config for your mod is the version before the latest thats because I thought I would try it and see if it fixed it, it did not..
Only having cruiseassist installed and nothing else it seemed to be fine...
It doesn't do it all the time it just seems to be random when it does it...

**Comment by tanukinomori** [comment]
I've tried the same mods and the same settings and didn't find any problems.
Do you have any idea how to cause the problem?

**Comment by NZ-Wanderer** [comment]
I don' know, as I said, it is just random, sometimes it does it sometimes it does not...

**Comment by NZ-Wanderer** [comment]
Good News....
It is NOT your mod... - A message was posted on Discord about the exact same problem says: Got a bug. I think it's from your multibuild mod. When I had the blueprints tab open and went into sail mode, the tab window was still up and blank the entire flight.
Sorry for all the trouble....
