### ISSUE TITLE
Names of Planets and Systems

### ISSUE THREAD

**Issue by NZ-Wanderer** [tanukinomori/DSPMod#2]
Sorry to bother you again, but was just wondering how hard it would be for your mod to display names of planets and Systems that have been renamed using (DSP_Planet_Rename and Starmapextension)

**Comment by tanukinomori** [comment]
If you want to talk about modding related to other mods, it's better to mention it on the DSP Modding discord server so we can work on it.

**Comment by NZ-Wanderer** [comment]
I'm sorry, I only mentioned it here because your mod only shows the original names of systems/planets even tho I have them renamed so I thought it would be something related to your mod..

**Comment by tanukinomori** [comment]
My mod displays the names of the stars using the system that is originally provided. I don't know how other mods change the names of stars, but my mod displays the original names as long as the names that can be obtained from the original system are not changed.

**Comment by NZ-Wanderer** [comment]
Ok, thank you...
