### ISSUE TITLE
Bug: CruiseAssist - NullReferenceException

### ISSUE THREAD

**Issue by Dumpshock** [tanukinomori/DSPMod#3]
Getting an error when using CruiseAssist to travel between star systems.

Error is generated when I get close to a destination star.   This happens whether I am using the assist or not and looks to be related to the UI itself?

From output_log.txt: 

> 
> Game save file wrote, time cost: 0.5419381s
>  
> (Filename: D:\unity\Runtime/Export/Debug.bindings.h Line: 45)
> 
> GameMain.Resume()
>  
> (Filename: D:\unity\Runtime/Export/Debug.bindings.h Line: 45)
> 
> [Info   :CruiseAssist] save config.
> Curl error 6: Could not resolve host: cdp.cloud.unity3d.com
> System.NullReferenceException: Object reference not set to an instance of an object
> at (wrapper dynamic-method) UISpaceGuide.DMD<UISpaceGuide.._OnLateUpdate> (UISpaceGuide) <0x0081a>
> at ManualBehaviour._LateUpdate () <0x0006a>
> 
>  
> (Filename: D:\unity\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Thread Log: 
> Vousk I
> Generate Terrain 0.15721 s
> Generate Vegetables 0.00000 s
> Generate Veins 0.00000 s
>

**Comment by tanukinomori** [comment]
Do you have any other mods on it?
Does it always happen every time?
Any other conditions that could cause the problem?

**Comment by tanukinomori** [comment]
Is this problem still occurring?

**Comment by Dumpshock** [comment]
Apologies, didn't have a chance to get back to this until now. 

Actually narrowed it down and it doesn't seem to be your mod, but an issue with Touhma_GalacticSCale it seems? 
Not sure why the logs seemed to suggest this was an issue coming from CruiseAssist, but it persisted even after disabling it.

https://github.com/Touhma/DSP_Plugins/issues/76
https://github.com/Touhma/DSP_Plugins/issues/74

I'll go ahead and close this as it doesn't seem relevant.
