### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cpjet64** [tanukinomori/DSPMod#4]
Love the mod it's amazing! Thank you for sharing it! Would it be possible to save the position of the windows if you move them or give direction for the config to preposition the windows?

**Comment by tanukinomori** [comment]
Already implemented window position saving, but is it different from that?

**Comment by cpjet64** [comment]
As long as I am in the game the window position saves but as soon as I restart the game the window position is back to the default top left corner.

**Comment by tanukinomori** [comment]
Saving the location information in a file named tanu.CruiseAssist.cfg, but it may not be working properly.
Can you attach the LogOutput.log and tanu.CruiseAssist.cfg?

**Comment by cpjet64** [comment]
Sorry for the delay I had to find where R2ModManager keeps those files!
If anyone else uses R2MM these are the locations in Windows.

%AppData%\r2modmanPlus-local\DysonSphereProgram\profiles\Modded\BepInEx\LogOutput.log
%AppData%\r2modmanPlus-local\DysonSphereProgram\profiles\Modded\BepInEx\config\tanu.CruiseAssist.cfg

[tanu.CruiseAssist.cfg.txt](https://github.com/tanukinomori/DSPMod/files/6215161/tanu.CruiseAssist.cfg.txt)
[LogOutput.log](https://github.com/tanukinomori/DSPMod/files/6215162/LogOutput.log)

**Comment by cpjet64** [comment]
I think there was corruption somewhere because when I just launched R2MM it called for a update for CruiseAssist and now the window positioning is working as you described. I will keep watch to see if the issue happens again. Thank you so much for the response to the issue I was having and once again I LOVE YOUR MOD!
