### ISSUE TITLE
Feature Request: Time to destination

### ISSUE THREAD

**Issue by cpjet64** [tanukinomori/DSPMod#5]
Can you make it where instead of only showing time to destination in seconds to where it shows in minutes and seconds
 if greater than 60 seconds? Also if greater than 60 minutes show time in hours and minutes?

![Screenshot_7](https://user-images.githubusercontent.com/38527447/112741281-591b8c80-8f52-11eb-950e-ddf66d4489da.png)

**Comment by tanukinomori** [comment]
Thank you for your request.
In the next update will add the display of hours, minutes and seconds to show the time to destination.

**Comment by tanukinomori** [comment]
Added in v0.0.20
