### ISSUE TITLE
Cruise Assist

### ISSUE THREAD

**Issue by seital** [tanukinomori/DSPMod#7]
Hello

First off thanks you for your work.

Really enjoyed CruiseAssist and would love to do so but starting to get a bug :/
https://i.imgur.com/S9E2zut.png
hope you can fix it soon :)

Thank you =)

**Comment by seital** [comment]
older save fixed the issue. dont know what it was tho.

**Comment by tanukinomori** [comment]
Please attach the LogOutput.log
